version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
            - MYSQL_DATABASE=myapp_development
            - MYSQL_ROOT_USER=root
            - MYSQL_ROOT_PASSWORD=passw0rd
            - TZ=Japan
  app:
    stdin_open: true
    tty: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .docker-env
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
